services:
  app:
    # 容器名称
    container_name: zhjh-next-app
    # 使用当前目录下的 Dockerfile 进行构建
    build:
      context: .
    # 端口映射：将主机的 80 端口映射到容器的 80 端口
    ports:
      - "80:80"
    # 重启策略：除非手动停止，否则容器总是在退出时重启
    restart: unless-stopped
    # 网络模式：使用 zhjh_network 网络
    networks:
      - zhjh_network

networks:
  zhjh_network:
    driver: bridge 